# Generated by Django 6.0.6 on 2026-06-17 10:34

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='uploadbatch',
            name='processed_records',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='uploadbatch',
            name='progress_percentage',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='uploadbatch',
            name='uploaded_file',
            field=models.FileField(default=django.utils.timezone.now, upload_to='bulk_uploads/'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='uploadbatch',
            name='invalid_records',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='uploadbatch',
            name='status',
            field=models.CharField(choices=[('uploaded', 'Uploaded'), ('processing', 'Processing'), ('validated', 'Validated'), ('completed', 'Completed'), ('failed', 'Failed')], default='uploaded', max_length=20),
        ),
        migrations.AlterField(
            model_name='uploadbatch',
            name='total_records',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='uploadbatch',
            name='valid_records',
            field=models.IntegerField(default=0),
        ),
    ]
