# Generated by Django 6.0.6 on 2026-06-18 10:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_uploadbatch_processed_records_and_more'),
    ]

    operations = [
        migrations.AddIndex(
            model_name='uploadbatchrecord',
            index=models.Index(fields=['email'], name='app_uploadb_email_5d3dc1_idx'),
        ),
        migrations.AddIndex(
            model_name='uploadbatchrecord',
            index=models.Index(fields=['batch', 'validation_status'], name='app_uploadb_batch_i_38e016_idx'),
        ),
        migrations.AddConstraint(
            model_name='uploadbatchrecord',
            constraint=models.UniqueConstraint(fields=('batch', 'row_number'), name='unique_batch_row'),
        ),
    ]
