# Generated by Django 6.0.6 on 2026-06-21 05:31

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0003_uploadbatchrecord_app_uploadb_email_5d3dc1_idx_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='registration',
            name='upload_batch',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='committed_registrations', to='app.uploadbatch'),
        ),
    ]
