# Generated by Django 5.1.2 on 2026-06-23 12:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0004_registration_upload_batch'),
    ]

operations = [
    migrations.AddField(
        model_name='tickettype',
        name='total_tickets',
        field=models.PositiveIntegerField(default=0),
    ),
]